# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiFile/broken.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 480)
        Dialog.setStyleSheet("background-color: rgba(238, 238, 236, 8);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setMinimumSize(QtCore.QSize(491, 0))
        self.widget.setMaximumSize(QtCore.QSize(491, 500))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(False)
        font.setWeight(50)
        self.widget.setFont(font)
        self.widget.setStyleSheet("border-radius:25px;\n"
"background-color: rgb(227, 227, 227);")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMaximumSize(QtCore.QSize(471, 480))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px")
        self.widget_2.setObjectName("widget_2")
        self.Label = QtWidgets.QLabel(self.widget_2)
        self.Label.setGeometry(QtCore.QRect(75, 80, 321, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Label.setFont(font)
        self.Label.setStyleSheet("color: rgb(192, 32, 52);")
        self.Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Label.setObjectName("Label")
        self.warning = QtWidgets.QTextBrowser(self.widget_2)
        self.warning.setGeometry(QtCore.QRect(35, 120, 401, 71))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(11)
        self.warning.setFont(font)
        self.warning.setStyleSheet("border-radius: 0px;\n"
"color: rgb(164, 0, 0);")
        self.warning.setObjectName("warning")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(0, -1, 471, 111))
        self.label_5.setStyleSheet("background-color: rgb(192, 32, 52 );\n"
"border-radius:20px;\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(0, 60, 471, 251))
        self.label_7.setStyleSheet("\n"
"border-radius:20px;\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.main_frame_3 = QtWidgets.QLabel(self.widget_2)
        self.main_frame_3.setGeometry(QtCore.QRect(0, 55, 471, 250))
        self.main_frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(186, 189, 182);\n"
"border-radius: 20px")
        self.main_frame_3.setText("")
        self.main_frame_3.setObjectName("main_frame_3")
        self.building = QtWidgets.QPushButton(self.widget_2)
        self.building.setGeometry(QtCore.QRect(155, 10, 160, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.building.setFont(font)
        self.building.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(192, 32, 52 );")
        self.building.setObjectName("building")
        self.back = QtWidgets.QPushButton(self.widget_2)
        self.back.setGeometry(QtCore.QRect(20, 15, 21, 31))
        self.back.setStyleSheet("border-radius: 25px;\n"
"image: url(:/newPrefix/previous.png);\n"
"background-color: rgb(192, 32, 52 );\n"
"")
        self.back.setText("")
        self.back.setObjectName("back")
        self.label_15 = QtWidgets.QLabel(self.widget_2)
        self.label_15.setEnabled(False)
        self.label_15.setGeometry(QtCore.QRect(80, 200, 110, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: rgba(60, 60, 60, 0);color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.rmt_btn_ = QtWidgets.QPushButton(self.widget_2)
        self.rmt_btn_.setEnabled(True)
        self.rmt_btn_.setGeometry(QtCore.QRect(20, 185, 211, 71))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.rmt_btn_.setFont(font)
        self.rmt_btn_.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: rgb(60, 60, 60);\n"
"   color: rgb(255, 255, 255);\n"
"   border-radius: 5px;\n"
"    border-bottom: 5px solid rgb(45, 45, 45);\n"
"}\n"
"")
        self.rmt_btn_.setText("")
        self.rmt_btn_.setObjectName("rmt_btn_")
        self.label_16 = QtWidgets.QLabel(self.widget_2)
        self.label_16.setEnabled(False)
        self.label_16.setGeometry(QtCore.QRect(80, 215, 151, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgba(60, 60, 60, 0);color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.widget_2)
        self.label_17.setEnabled(False)
        self.label_17.setGeometry(QtCore.QRect(80, 285, 110, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color: rgba(60, 60, 60, 0);color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.rmt_btn_1 = QtWidgets.QPushButton(self.widget_2)
        self.rmt_btn_1.setEnabled(True)
        self.rmt_btn_1.setGeometry(QtCore.QRect(20, 270, 211, 71))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.rmt_btn_1.setFont(font)
        self.rmt_btn_1.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: rgb(60, 60, 60);\n"
"   color: rgb(255, 255, 255);\n"
"   border-radius: 5px;\n"
"    border-bottom: 5px solid rgb(45, 45, 45);\n"
"}\n"
"")
        self.rmt_btn_1.setText("")
        self.rmt_btn_1.setObjectName("rmt_btn_1")
        self.label_18 = QtWidgets.QLabel(self.widget_2)
        self.label_18.setEnabled(False)
        self.label_18.setGeometry(QtCore.QRect(80, 300, 151, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgba(60, 60, 60, 0);color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.widget_2)
        self.label_19.setEnabled(False)
        self.label_19.setGeometry(QtCore.QRect(300, 285, 110, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgba(60, 60, 60, 0);color: rgb(255, 255, 255);")
        self.label_19.setObjectName("label_19")
        self.rmt_btn_2 = QtWidgets.QPushButton(self.widget_2)
        self.rmt_btn_2.setEnabled(True)
        self.rmt_btn_2.setGeometry(QtCore.QRect(240, 270, 211, 71))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.rmt_btn_2.setFont(font)
        self.rmt_btn_2.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: rgb(60, 60, 60);\n"
"   color: rgb(255, 255, 255);\n"
"   border-radius: 5px;\n"
"    border-bottom: 5px solid rgb(45, 45, 45);\n"
"}\n"
"")
        self.rmt_btn_2.setText("")
        self.rmt_btn_2.setObjectName("rmt_btn_2")
        self.label_20 = QtWidgets.QLabel(self.widget_2)
        self.label_20.setEnabled(False)
        self.label_20.setGeometry(QtCore.QRect(300, 300, 151, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: rgba(60, 60, 60, 0);color: rgb(255, 255, 255);")
        self.label_20.setObjectName("label_20")
        self.lsr_btn_ = QtWidgets.QPushButton(self.widget_2)
        self.lsr_btn_.setEnabled(True)
        self.lsr_btn_.setGeometry(QtCore.QRect(240, 185, 211, 71))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lsr_btn_.setFont(font)
        self.lsr_btn_.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: rgb(60, 60, 60);\n"
"   color: rgb(255, 255, 255);\n"
"   border-radius: 5px;\n"
"    border-bottom: 5px solid rgb(45, 45, 45);\n"
"}\n"
"")
        self.lsr_btn_.setText("")
        self.lsr_btn_.setObjectName("lsr_btn_")
        self.label_21 = QtWidgets.QLabel(self.widget_2)
        self.label_21.setEnabled(False)
        self.label_21.setGeometry(QtCore.QRect(300, 200, 110, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color: rgba(60, 60, 60, 0);color: rgb(255, 255, 255);")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.widget_2)
        self.label_22.setEnabled(False)
        self.label_22.setGeometry(QtCore.QRect(300, 215, 151, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: rgba(60, 60, 60, 0);color: rgb(255, 255, 255);")
        self.label_22.setObjectName("label_22")
        self.del_remote = QtWidgets.QPushButton(self.widget_2)
        self.del_remote.setGeometry(QtCore.QRect(30, 205, 35, 35))
        self.del_remote.setStyleSheet("image: url(:/newPrefix/minus.png);\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 1px;")
        self.del_remote.setText("")
        self.del_remote.setObjectName("del_remote")
        self.del_laser = QtWidgets.QPushButton(self.widget_2)
        self.del_laser.setGeometry(QtCore.QRect(250, 205, 35, 35))
        self.del_laser.setStyleSheet("image: url(:/newPrefix/minus.png);\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 1px;")
        self.del_laser.setText("")
        self.del_laser.setObjectName("del_laser")
        self.del_hdmi = QtWidgets.QPushButton(self.widget_2)
        self.del_hdmi.setGeometry(QtCore.QRect(30, 290, 35, 35))
        self.del_hdmi.setStyleSheet("image: url(:/newPrefix/minus.png);\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 1px;")
        self.del_hdmi.setText("")
        self.del_hdmi.setObjectName("del_hdmi")
        self.del_micro = QtWidgets.QPushButton(self.widget_2)
        self.del_micro.setGeometry(QtCore.QRect(250, 290, 35, 35))
        self.del_micro.setStyleSheet("image: url(:/newPrefix/minus.png);\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 1px;")
        self.del_micro.setText("")
        self.del_micro.setObjectName("del_micro")
        self.remote_room = QtWidgets.QLabel(self.widget_2)
        self.remote_room.setGeometry(QtCore.QRect(180, 180, 41, 21))
        self.remote_room.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 2px;")
        self.remote_room.setText("")
        self.remote_room.setAlignment(QtCore.Qt.AlignCenter)
        self.remote_room.setObjectName("remote_room")
        self.laser_room = QtWidgets.QLabel(self.widget_2)
        self.laser_room.setGeometry(QtCore.QRect(400, 180, 41, 21))
        self.laser_room.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 2px;")
        self.laser_room.setText("")
        self.laser_room.setAlignment(QtCore.Qt.AlignCenter)
        self.laser_room.setObjectName("laser_room")
        self.hdmi_room = QtWidgets.QLabel(self.widget_2)
        self.hdmi_room.setGeometry(QtCore.QRect(180, 265, 41, 21))
        self.hdmi_room.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 2px;")
        self.hdmi_room.setText("")
        self.hdmi_room.setAlignment(QtCore.Qt.AlignCenter)
        self.hdmi_room.setObjectName("hdmi_room")
        self.micro_room = QtWidgets.QLabel(self.widget_2)
        self.micro_room.setGeometry(QtCore.QRect(400, 265, 41, 21))
        self.micro_room.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 2px;")
        self.micro_room.setText("")
        self.micro_room.setAlignment(QtCore.Qt.AlignCenter)
        self.micro_room.setObjectName("micro_room")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(30, 205, 35, 35))
        self.label_3.setStyleSheet("background-color: rgb(200, 200, 200);\n"
"border-radius: 1px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(250, 205, 35, 35))
        self.label_4.setStyleSheet("background-color: rgb(200, 200, 200);\n"
"border-radius: 1px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(30, 290, 35, 35))
        self.label_6.setStyleSheet("background-color: rgb(200, 200, 200);\n"
"border-radius: 1px;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(250, 290, 35, 35))
        self.label_8.setStyleSheet("background-color: rgb(200, 200, 200);\n"
"border-radius: 1px;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(110, 360, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton:hover {\n"
"\n"
"    background-color: rgb(182, 22, 42);\n"
"   color: rgb(255, 255, 255);\n"
"   border-radius: 15px; \n"
"}\n"
"QPushButton {\n"
"\n"
"    background-color: rgb(202, 42, 62);\n"
"   color: rgb(255, 255, 255);\n"
"   border-radius: 15px;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.done = QtWidgets.QLabel(self.widget_2)
        self.done.setGeometry(QtCore.QRect(30, 360, 61, 61))
        self.done.setStyleSheet("image: url(:/newPrefix/accept.png);")
        self.done.setText("")
        self.done.setObjectName("done")
        self.label_5.raise_()
        self.main_frame_3.raise_()
        self.label_7.raise_()
        self.Label.raise_()
        self.warning.raise_()
        self.building.raise_()
        self.back.raise_()
        self.rmt_btn_.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.rmt_btn_1.raise_()
        self.label_18.raise_()
        self.rmt_btn_2.raise_()
        self.label_20.raise_()
        self.label_17.raise_()
        self.label_19.raise_()
        self.lsr_btn_.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.remote_room.raise_()
        self.laser_room.raise_()
        self.hdmi_room.raise_()
        self.micro_room.raise_()
        self.label_3.raise_()
        self.del_remote.raise_()
        self.label_4.raise_()
        self.del_laser.raise_()
        self.label_6.raise_()
        self.del_hdmi.raise_()
        self.label_8.raise_()
        self.del_micro.raise_()
        self.pushButton.raise_()
        self.done.raise_()
        self.gridLayout_2.addWidget(self.widget_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Label.setText(_translate("Dialog", "THÔNG BÁO THIẾT BỊ LỖI"))
        self.warning.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Thầy cô vui lòng quét chọn thiết bị lỗi để đội ngũ kỹ thuật sửa chữa thiết bị trong thời gian sớm nhất!</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.building.setText(_translate("Dialog", "HUST D6"))
        self.label_15.setText(_translate("Dialog", "THIẾT BỊ"))
        self.label_16.setText(_translate("Dialog", "ĐIỀU KHIỂN "))
        self.label_17.setText(_translate("Dialog", "THIẾT BỊ"))
        self.label_18.setText(_translate("Dialog", "CÁP HDMI"))
        self.label_19.setText(_translate("Dialog", "THIẾT BỊ"))
        self.label_20.setText(_translate("Dialog", "MICRO"))
        self.label_21.setText(_translate("Dialog", "THIẾT BỊ"))
        self.label_22.setText(_translate("Dialog", "BÚT LASER"))
        self.pushButton.setText(_translate("Dialog", "BÁO CÁO"))
import Images_rc
